import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { ScreenContainer } from "@/components/screen-container";
import { SatarkMark } from "@/components/satark-mark";
import { appLanguages, useAppLanguage, type AppLanguage } from "@/lib/app-language";

const points = [
  { icon: "psychology-alt", title: ["Looks beyond a number", "सिर्फ नंबर से आगे देखता है", "फक्त नंबरच्या पलीकडे पाहते"], text: ["Satark AI reads pressure, impersonation, and urgency inside a message — signals a number-only blocker cannot see.", "सतर्क AI संदेश में दबाव, नकल और जल्दी कराने के संकेत देखता है।", "सतर्क AI संदेशातील दबाव, नक्कल आणि घाईचे संकेत ओळखते."] },
  { icon: "language", title: ["Choose your language", "अपनी भाषा चुनें", "तुमची भाषा निवडा"], text: ["Use Hindi, Marathi, or English for the app interface and analysis output.", "ऐप और विश्लेषण के लिए हिंदी, मराठी या English चुनें।", "अॅप आणि विश्लेषणासाठी हिंदी, मराठी किंवा English निवडा."] },
  { icon: "shield", title: ["A pause before you act", "कदम उठाने से पहले ठहरें", "कृती करण्यापूर्वी थांबा"], text: ["A risk score is a prompt to verify independently, not proof that a person or business is unsafe.", "जोखिम स्कोर अलग से जांचने का संकेत है, पक्का सबूत नहीं।", "धोका स्कोअर स्वतंत्रपणे तपासण्याचा इशारा आहे, खात्रीशीर पुरावा नाही."] },
];

export default function AboutScreen() {
  const { language, setLanguage, t, languageLabel } = useAppLanguage();
  const languageIndex = language === "english" ? 0 : language === "hindi" ? 1 : 2;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.brandRow}><View style={styles.markWrap}><SatarkMark size={36} /></View><View><Text style={styles.brand}>SATARK <Text style={styles.brandAI}>AI</Text></Text><Text style={styles.tagline}>See the Risk. Stay सतर्क.</Text></View></View>
    <Text style={styles.title}>{t.aboutTitle}</Text><Text style={styles.copy}>{t.aboutCopy}</Text><View style={styles.divider} />
    <Text style={styles.sectionLabel}>{t.appLanguage}</Text><View style={styles.languagePicker}>{appLanguages.map((option) => <Pressable key={option} onPress={() => setLanguage(option)} style={({ pressed }) => [styles.languageChoice, language === option && styles.languageChoiceActive, pressed && styles.pressed]}><Text style={[styles.languageChoiceText, option !== "english" && styles.devanagari, language === option && styles.languageChoiceTextActive]}>{languageLabel(option)}</Text></Pressable>)}</View>
    <View style={styles.divider} /><Text style={styles.sectionLabel}>{t.whatWeLookFor}</Text>{points.map((point) => <View key={point.title[0]} style={styles.point}><View style={styles.pointIcon}><MaterialIcons name={point.icon as never} size={21} color="#FF9500" /></View><View style={styles.pointCopy}><Text style={[styles.pointTitle, language !== "english" && styles.devanagari]}>{point.title[languageIndex]}</Text><Text style={[styles.pointText, language !== "english" && styles.devanagari]}>{point.text[languageIndex]}</Text></View></View>)}
    <View style={styles.notice}><MaterialIcons name="lock-outline" size={19} color="#F5C451" /><Text style={[styles.noticeText, language !== "english" && styles.devanagari]}>{t.privacyNotice}</Text></View>
  </ScrollView></ScreenContainer>;
}

const styles: Record<string, any> = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 108 }, brandRow: { flexDirection: "row", alignItems: "center", gap: 10 }, markWrap: { width: 54, height: 54, justifyContent: "center", alignItems: "center", backgroundColor: "#171720", borderWidth: 1, borderColor: "#302E38", borderRadius: 18 }, brand: { color: "#F5F5F7", fontFamily: "SpaceGrotesk_700Bold", fontSize: 20, letterSpacing: -0.4 }, brandAI: { color: "#FF9500" }, tagline: { color: "#A8A6B3", fontFamily: "Inter_400Regular", fontSize: 12.5, marginTop: 2 }, title: { color: "#F5F5F7", fontFamily: "SpaceGrotesk_700Bold", fontSize: 32, lineHeight: 39, letterSpacing: -0.9, marginTop: 31 }, copy: { color: "#B7B5C0", fontFamily: "Inter_400Regular", fontSize: 15.5, lineHeight: 23, marginTop: 12 }, divider: { height: 1, backgroundColor: "#292934", marginVertical: 28 }, sectionLabel: { color: "#FF9500", fontFamily: "Rajdhani_600SemiBold", fontSize: 11, letterSpacing: 1.3, marginBottom: 13 }, languagePicker: { flexDirection: "row", gap: 7 }, languageChoice: { flex: 1, borderRadius: 12, borderWidth: 1, borderColor: "#30303A", paddingVertical: 10, alignItems: "center", backgroundColor: "#101017" }, languageChoiceActive: { borderColor: "#FF9500", backgroundColor: "#2A1D0A" }, languageChoiceText: { color: "#A8A6B3", fontFamily: "Inter_600SemiBold", fontSize: 12 }, languageChoiceTextActive: { color: "#FFB451" }, pressed: { opacity: 0.7 }, point: { flexDirection: "row", gap: 13, marginBottom: 21 }, pointIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#241C12", justifyContent: "center", alignItems: "center" }, pointCopy: { flex: 1 }, pointTitle: { color: "#F5F5F7", fontFamily: "SpaceGrotesk_600SemiBold", fontSize: 15.5, marginTop: 1 }, pointText: { color: "#A8A6B3", fontFamily: "Inter_400Regular", fontSize: 13.5, lineHeight: 20, marginTop: 4 }, notice: { flexDirection: "row", gap: 10, padding: 15, borderRadius: 16, backgroundColor: "#26231A", borderWidth: 1, borderColor: "#4A412A", marginTop: 6 }, noticeText: { color: "#D2C99B", fontFamily: "Inter_500Medium", fontSize: 12.5, lineHeight: 18, flex: 1 }, devanagari: { fontFamily: "NotoSansDevanagari_400Regular", lineHeight: 22 } });
